### ISSUE TITLE
Library\PackageCache\com.unitynative.toasts@ac09d7fc59\UnityNativeToasts.cs(39,46): error CS0246: The type or namespace name 'NullUnityNativeToastsAdapter' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by dev-magesstudio** [NicholasSheehan/Unity-Native-Toasts#3]

**Comment by NicholasSheehan** [comment]
Copied from https://github.com/NicholasSheehan/Unity-Native-Toasts/pull/4

Thanks for spotting this issue

This PR will fix the error, it doesn't solve the issue

The class name in [NullUnityNativeToastsAdapter.cs](https://github.com/NicholasSheehan/Unity-Native-Toasts/blob/master/Adapters/NullUnityNativeToastsAdapter.cs) was not renamed while refactoring, the class name needs to be changed to `NullUnityNativeToastsAdapter` from `NullUnityNativeSharingAdapter`

I'll have a look at this when I wake up to make sure nothing else has been missed

**Comment by NicholasSheehan** [comment]
Fixed in `v1.0.3` and closed #4
