### ISSUE TITLE
Toast on ios blocks all UI elements

### ISSUE THREAD

**Issue by sughosh-mages** [NicholasSheehan/Unity-Native-Toasts#5]
Hello,
I am using your toast plugin to create ios notification toasts. When they render on screen, it is disabling all UI elements, Is there any way around this? Works perfectly on Android.

**Comment by NicholasSheehan** [comment]
Hi, sorry that hear that you're having issues

When you say it disables all UI elements, what exactly do you mean?

Is it just Unity UI elements?

**Comment by sughosh-mages** [comment]
Hi Nicholas,
Thank you for the quick response. 
Yes. Native UI elements like inputbox and buttons.
Attaching a ref image how toasts are shown in ios. (very different from the small toast on the bottom of screen like in ios)
![Image from iOS](https://user-images.githubusercontent.com/52438764/91731658-bae66480-ebc4-11ea-9c5c-f89d0361e3ab.png)

The toast is blocking the input field and the button. Though as soon as the toast disappears, everything works fine.

**Comment by NicholasSheehan** [comment]
I think i know what the issue is, but it would require me to re-write the iOS side, so I'm not sure how long it'd take.

Once I have something I'll reply with the branch it's on for you to test

**Comment by NicholasSheehan** [comment]
I just pushed the branch [v1.0.4_iOS](https://github.com/NicholasSheehan/Unity-Native-Toasts/tree/release/v1.0.4_iOS)

This shouldn't block input, but the look of the toasts have changed, functionally it doesn't block the UI inputs anymore

I have a small todo list of things with this repo, one of them is getting the look and feel as close to Android as possible

**Comment by sughosh-mages** [comment]
Thanks a lot Nicholas! 
I will test this and let you know 👍 
Cheers,
Fellow Developer

**Comment by NicholasSheehan** [comment]
Hi, did the new branch work?

**Comment by sughosh-mages** [comment]
Hi Nicholas! Sorry for late reply.
Branch works perfectly! Thank you soo much!
You can close this now :)
Cheers
