### ISSUE TITLE
  Duplicate class com.UnityNative.Toasts.UnityNativeToastsAdapter found in modules classes.jar (:com.UnityNative.Toasts-v1.0.3:) and classes.jar (:com.UnityNative.Toasts-v1.0.4:)

### ISSUE THREAD

**Issue by dclipca** [NicholasSheehan/Unity-Native-Toasts#6]

**Comment by dclipca** [comment]
Hi! I am getting this error when building for Android:
```
  Duplicate class com.UnityNative.Toasts.UnityNativeToastsAdapter found in modules classes.jar (:com.UnityNative.Toasts-v1.0.3:) and classes.jar (:com.UnityNative.Toasts-v1.0.4:)

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)

  java.lang.RuntimeException: Duplicate class com.UnityNative.Toasts.BuildConfig found in modules classes.jar (:com.UnityNative.Toasts-v1.0.3:) and classes.jar (:com.UnityNative.Toasts-v1.0.4:)

UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)
```

What might be the root issue?

**Comment by NicholasSheehan** [comment]
I may have forgotten to delete the v1.0.3 aar

Deleting the v1.0.3 aar should solve the issue

**Comment by NicholasSheehan** [comment]
Once im back at my computer ill fix and update. But for now deleting the v1.0.3 aar will fix the issue

**Comment by dclipca** [comment]
Thank you for the fast response! You are right, it does work after deleting the old version.

Thanks for the library by the way. I find it very helpful.

**Comment by NicholasSheehan** [comment]
Deleted the old .aar and amended the commit, should be all good

**Comment by virtumonde** [comment]
I am using this plugin like this:
```
UnityNativeToastsHelper.ShowLongToast("this is the error");
```
but there are no effects on Android (no toast). Is this the correct way to use it?

**Comment by virtumonde** [comment]
Nevermind, everything works as expected. Is there a chance there would be an option to change the position of the toast in the near future?
